version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
      target: production
    tty: true
    env_file:
      - .env
    expose:
      - '${BACKEND_PORT}'
    depends_on:
      - db
    command: sh -c "yarn prisma migrate deploy && node dist/main.js"
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
      target: production
    tty: true
    env_file:
      - .env
    expose:
      - '80'
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      # Remember to change those to secure vault parameters!
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pwd
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - '5432'
    restart: always

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      # Remember to change those to secure vault parameters!
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin_pwd
      PGADMIN_LISTEN_PORT: 3000
    expose:
      - '80'
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: proxy_nginx
    depends_on:
      - backend
      - db
      - pgadmin
    ports:
      - '3000:80'
    volumes:
      - ./nginx/nginx.proxy.conf:/etc/nginx/conf.d/default.conf
    restart: always